disabled_rules:
  - contrasted_opening_brace
  - explicit_acl
  - explicit_top_level_acl
  - accessibility_label_for_image

opt_in_rules:
  - all

indentation_width:
  indentation_width: 2

line_length:
  warning: 140
  ignores_comments: true
